In [415]:
%load_ext autoreload
%autoreload 2

from torch import nn

import torch.nn.functional as F
import torch

from utils_external.sync_batchnorm import SynchronizedBatchNorm2d as BatchNorm2d
from utils_external.sync_batchnorm import SynchronizedBatchNorm3d as BatchNorm3d

from utils import Encoder, Decoder

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [416]:
from keypoint_detector import KPDetector, Hourglass

In [417]:
%reload_ext autoreload

In [398]:
y = torch.randn([10,3,256,256])

In [399]:
x = torch.randn([10,3,1,256,256])

In [400]:
c = Encoder(in_features=3, max_features=1024, block_expansion=32,dimension=2)

In [401]:
d = Decoder(in_features=3, max_features=1024, block_expansion=32, dimension=2, out_features=10)

In [249]:
d(c(y)).shape

torch.Size([10, 10, 256, 256])

In [251]:
from IPython.lib.deepreload import reload
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [252]:
%reload_ext autoreload

In [253]:
x.shape

torch.Size([10, 3, 1, 256, 256])

In [418]:
x = torch.randn([10,3,1, 256,256])

In [411]:
a = Hourglass(dimension=2, num_kp=10)

In [420]:
heatmap_3d = a(x)

In [421]:
heatmap_3d.shape

torch.Size([10, 10, 1, 256, 256])

In [391]:
tmp_1 = F.interpolate(x, scale_factor=(0.25, 0.25))
tmp_1.shape

ValueError: scale_factor shape must match input shape. Input is 3D, scale_factor is 2

In [256]:
a= Hourglass(dimension=2, num_kp=10)

In [257]:
heatmap = a(x)
heatmap.shape

final_shape = heatmap.shape

In [258]:
heatmap = heatmap.view(final_shape[0], final_shape[1], -1)
heatmap.shape

torch.Size([10, 10, 65536])

In [259]:
heatmap_tmp = F.softmax(heatmap / 0.1, dim=2)
heatmap_tmp.shape

torch.Size([10, 10, 65536])

In [234]:
heatmap_tmp[0][0]

tensor([2.5754e-09, 6.7504e-11, 2.1276e-10,  ..., 4.2270e-08, 1.4624e-07,
        6.2656e-10], grad_fn=<SelectBackward>)

In [351]:
heatmap_tmp = F.softmax(heatmap / 0.5, dim=2)
heatmap_tmp.shape
heatmap_tmp[0][0]

tensor([[0.0022, 0.0069, 0.0059,  ..., 0.0155, 0.0047, 0.0031],
        [0.0021, 0.0051, 0.0044,  ..., 0.0068, 0.0018, 0.0012],
        [0.0032, 0.0058, 0.0068,  ..., 0.0027, 0.0038, 0.0035],
        ...,
        [0.0054, 0.0069, 0.0034,  ..., 0.0022, 0.0010, 0.0014],
        [0.0024, 0.0029, 0.0023,  ..., 0.0011, 0.0017, 0.0054],
        [0.0048, 0.0020, 0.0019,  ..., 0.0017, 0.0018, 0.0041]],
       grad_fn=<SelectBackward>)

In [352]:
heatmap_tmp = heatmap_tmp.view(*final_shape)
heatmap_tmp.shape

torch.Size([10, 10, 256, 256])

In [353]:
shape  = heatmap_tmp.shape
aaa = heatmap_tmp.unsqueeze(-1)
aaa.shape

torch.Size([10, 10, 256, 256, 1])

In [354]:
grid = make_coordinate_grid(heatmap_tmp.shape[2:], heatmap_tmp.type()).unsqueeze_(0).unsqueeze_(0)
grid.shape

torch.Size([1, 1, 256, 256, 2])

In [371]:
grid[0][0]

tensor([[[-1.0000, -1.0000],
         [-0.9922, -1.0000],
         [-0.9843, -1.0000],
         ...,
         [ 0.9843, -1.0000],
         [ 0.9922, -1.0000],
         [ 1.0000, -1.0000]],

        [[-1.0000, -0.9922],
         [-0.9922, -0.9922],
         [-0.9843, -0.9922],
         ...,
         [ 0.9843, -0.9922],
         [ 0.9922, -0.9922],
         [ 1.0000, -0.9922]],

        [[-1.0000, -0.9843],
         [-0.9922, -0.9843],
         [-0.9843, -0.9843],
         ...,
         [ 0.9843, -0.9843],
         [ 0.9922, -0.9843],
         [ 1.0000, -0.9843]],

        ...,

        [[-1.0000,  0.9843],
         [-0.9922,  0.9843],
         [-0.9843,  0.9843],
         ...,
         [ 0.9843,  0.9843],
         [ 0.9922,  0.9843],
         [ 1.0000,  0.9843]],

        [[-1.0000,  0.9922],
         [-0.9922,  0.9922],
         [-0.9843,  0.9922],
         ...,
         [ 0.9843,  0.9922],
         [ 0.9922,  0.9922],
         [ 1.0000,  0.9922]],

        [[-1.0000,  1.0000],
       

IndexError: index 1 is out of bounds for dimension 0 with size 1

In [356]:
(aaa * grid).shape

torch.Size([10, 10, 256, 256, 2])

In [357]:
(aaa * grid).sum(dim=(2,3)).shape

torch.Size([10, 10, 2])

In [387]:
mean = (aaa * grid).sum(dim=(2, 3))

In [388]:
mean.shape

torch.Size([10, 10, 2])

In [376]:
grid.shape

torch.Size([1, 1, 256, 256, 2])

In [389]:
mean.permutate(0,2,1,3)

AttributeError: 'Tensor' object has no attribute 'permutate'

In [385]:
mean.unsqueeze(0).unsqueeze(0).shape

torch.Size([1, 1, 10, 10, 2])

In [386]:
grid - mean

RuntimeError: The size of tensor a (256) must match the size of tensor b (10) at non-singleton dimension 3

In [382]:
grid.shape

torch.Size([1, 1, 256, 256, 2])

In [341]:
heatmap_tmp.unsqueeze(-1)
heatmap_tmp.shape

torch.Size([10, 10, 256, 256])

In [ ]:
make_coordinate_grid(heatmap_tmp.shape[2:], aaa.type())

In [350]:
heatmap_tmp.shape[2:]

torch.Size([256, 256])

In [349]:
h, w = heatmap_tmp.shape[2:]
x = torch.arange(w).type(aaa.type())
y = torch.arange(h).type(aaa.type())

x.shape, y.shape

(torch.Size([256]), torch.Size([256]))

In [296]:
x = (2 * (x / (w - 1)) - 1)
y = (2 * (y / (h - 1)) - 1)

In [297]:
y.shape

torch.Size([256])

In [327]:
yy = y.view(-1, 1).repeat(1, w)
yy.shape

torch.Size([256, 256])

In [328]:
yy

tensor([[-1.0000, -1.0000, -1.0000,  ..., -1.0000, -1.0000, -1.0000],
        [-0.9922, -0.9922, -0.9922,  ..., -0.9922, -0.9922, -0.9922],
        [-0.9843, -0.9843, -0.9843,  ..., -0.9843, -0.9843, -0.9843],
        ...,
        [ 0.9843,  0.9843,  0.9843,  ...,  0.9843,  0.9843,  0.9843],
        [ 0.9922,  0.9922,  0.9922,  ...,  0.9922,  0.9922,  0.9922],
        [ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000]])

In [329]:
xx = x.view(1, -1).repeat(h, 1)
xx.shape

torch.Size([256, 256])

In [348]:
xx.shape

torch.Size([256, 256, 1, 1])

In [344]:
meshed = torch.cat([xx.unsqueeze_(2), yy.unsqueeze_(2)], 2)
meshed.shape

torch.Size([256, 256, 2, 1])

In [345]:
meshed = meshed.unsqueeze_(0).unsqueeze_(0)
meshed.shape

torch.Size([1, 1, 256, 256, 2, 1])

In [346]:
meshed.squeeze_(-1)
meshed.shape

torch.Size([1, 1, 256, 256, 2])

In [318]:
meshed.unsqueeze_(0).unsqueeze_(0).unsqueeze_(0).shape

torch.Size([1, 1, 1, 1, 1, 1, 256, 256, 2])

In [312]:
heatmap_tmp.shape

torch.Size([10, 10, 256, 256])

In [347]:
(heatmap_tmp * meshed).shape

RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 4

In [310]:
mean = (heatmap_tmp * meshed).sum(dim=(2,3))
mean.shape

RuntimeError: The size of tensor a (256) must match the size of tensor b (2) at non-singleton dimension 3

In [ ]:
make_coordinate_grid(shape[2:], heatmap.type())

In [261]:
def gaussian2kp_2d(heatmap):
    """
    Extract the mean and from a heatmap
    """
    shape = heatmap.shape
    heatmap = heatmap.unsqueeze(-1)
    grid = make_coordinate_grid(shape[2:], heatmap.type()).unsqueeze_(0).unsqueeze_(0)
    value = (heatmap * grid).sum(dim=(2, 3))
    kp = {'value': value}

    return kp


In [269]:
out = gaussian2kp_2d(heatmap)

NameError: name 'make_coordinate_grid' is not defined

In [265]:
shape = heatmap.shape
shape

torch.Size([10, 10, 256, 256])

In [266]:
heatmap.type()

'torch.FloatTensor'

In [272]:
h, w = shape
type = heatmap.type()

ValueError: too many values to unpack (expected 2)

In [270]:
def make_coordinate_grid(spatial_size, type):
    """
    Create a meshgrid [-1,1] x [-1,1] of given spatial_size.
    """
    h, w = spatial_size
    x = torch.arange(w).type(type)
    y = torch.arange(h).type(type)

    x = (2 * (x / (w - 1)) - 1)
    y = (2 * (y / (h - 1)) - 1)

    yy = y.view(-1, 1).repeat(1, w)
    xx = x.view(1, -1).repeat(h, 1)

    meshed = torch.cat([xx.unsqueeze_(2), yy.unsqueeze_(2)], 2)

    return meshed

In [ ]:
make_coordinate_grid(shape[2:], heatmap.type())

In [200]:
N, W = 4, 5
bag = [(2,3), (3,4), (4,5), (5,6)] # (weight,benefit) 순서

knap = [0 for _ in range(W+1)]

for i in range(N):
    for j in range(W, 1, -1):
        if bag[i][0] <= j:
            knap[j] = max(knap[j], knap[j-bag[i][0]] + bag[i][1])

print(knap)

[0, 0, 3, 4, 5, 7]


In [268]:
def printknapSack(W, wt, val, n):
    K = [[0 for w in range(W + 1)]
            for i in range(n + 1)]
             
    # Build table K[][] in bottom
    # up manner
    for i in range(n + 1):
        for w in range(W + 1):
            if i == 0 or w == 0:
                K[i][w] = 0
            elif wt[i - 1] <= w:
                K[i][w] = max(val[i - 1]
                  + K[i - 1][w - wt[i - 1]],
                               K[i - 1][w])
            else:
                K[i][w] = K[i - 1][w]
 
    # stores the result of Knapsack
    res = K[n][W]
    print(res)
     
    w = W
    for i in range(n, 0, -1):
        if res <= 0:
            break
        # either the result comes from the
        # top (K[i-1][w]) or from (val[i-1]
        # + K[i-1] [w-wt[i-1]]) as in Knapsack
        # table. If it comes from the latter
        # one/ it means the item is included.
        if res == K[i - 1][w]:
            continue
        else:
 
            # This item is included.
            print(wt[i - 1])
             
            # Since this weight is included
            # its value is deducted
            res = res - val[i - 1]
            w = w - wt[i - 1]

            
val = [10200, 9800, 4300,10200, 9800, 4300,10200, 9800, 4300,10200, 9800, 4300]
wt = [10200, 9800, 4300,10200, 9800, 4300,10200, 9800, 4300,10200, 9800, 4300]
W = 64800
n = len(val)
     
printknapSack(W, wt, val, n)

64700
10200
10200
9800
10200
4300
9800
10200


In [227]:
4300*4 + 9800*4 + 

64700

In [176]:
kp = KPDetector(block_expansion=32, num_kp=10, num_channels=3, max_features=1024, num_blocks=5, temperature=0.1, kp_variance='matrix')

In [177]:
x = torch.randn([10,3,256,256])

In [178]:
kp(x)

NameError: name 'make_coordinate_grid' is not defined

In [179]:
spatial_size = (256, 256)
h, w = spatial_size

In [180]:
x = torch.arange(w).type(type)
y = torch.arange(h).type(type)

ValueError: invalid type: 'type'